### PR TITLE
Mysql fix

### LINKED ISSUE #389: MySQL/MariaDB users can not upgrade to the latest version 4.12
The database update 20170626074649_add_note_annotations_index.rb tries to execute
```
CREATE  INDEX `index_note_annotations_on_value`  ON `note_annotations` (`value`)
```
on my MySQL database. This fails as as for InnoDB tables there is a maximum key length of 767 bytes. This means, indexed fields consisting of UTF8 columns must not exceed a length of 191 bytes (767/4).

I didn't see any content longer than 24 characters in my existing DB, so I resized the column prior to run the upgrade scripts.

### PR DESCRIPTION
**Pull request by philippneugebauer**
fixes #389

### CODE REVIEW

File: db/migrate/20180525135715_fix_note_annotations_index.rb [hunk 1]
```diff
@@ -0,0 +1,6 @@
+class FixNoteAnnotationsIndex < ActiveRecord::Migration
+  def change
+    remove_index :note_annotations, :value if index_exists? :note_annotations, :value
```
Comment (mjansing) [inline db/migrate/20180525135715_fix_note_annotations_index.rb]: Here is a little gotcha: remove_index is only reversible if a given column option

**Comment by mjansing** [comment]
I fixed this irreversible migration and tested this code with a plain new database and our umthes. Good work.
